# Generated by Django 4.2.7 on 2023-11-15 15:04

import app_catalogo_veiculos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id_carro', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('marca', models.TextField(max_length=255)),
                ('ano', models.IntegerField()),
                ('image', models.ImageField()),
                ('preco', models.FloatField()),
            ],
        ),
    ]
