# Generated by Django 4.2.7 on 2023-11-15 15:27

import app_catalogo_veiculos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalogo_veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='image',
            field=models.ImageField(),
        ),
    ]
